### ISSUE TITLE
Water in Nodes

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/NodeGateway#6]
Paula has set up 4 nodes outside Week of Dec 9 to Dec 20, 2019.
2 of them have a lot of water inside.
The seal of the box enclosure (where there is a soft gasket, not the seal of the solar panel) appears to be leaking, and maybe from other areas too.
Paula, do you have more comments?

**Comment by alondrathompson** [comment]
Is it possible that one of the solar panel wires got caught in the door so it didn't seal?

**Comment by hschomberg** [comment]
Are the rubber gaskets in the lid intact? Do they have any missing chunks etc. Were openings at the bottom of the box sealed with electric putty? Is it possible the water came in through the antenna opening. Are the antenna securely tightened to the enclosure?   

Could this be condensation?

**Comment by paularamo** [comment]
We have had rainy days. Initially, I only saw one node with water inside, the other nodes and gateways were dry. And I thought it might be the silicone that joins the solar panel to the box and the hole where the cables from the solar panel enter the box. 

Today doing the reinstallation of the firmware, I noted another node with a lot of water inside. They could be the rubber gaskets of the box because that's where the water comes from. Condensation I don't think (in this case), I touched the pipe and it's dry if it was mainly condensation the pipe should be wet too. The hole in the lid for the solar panel is dry and the wires that go into the box too. I think we should test the seal of the box joints and seal all the holes where the cables enter. Also, we should put a lot of silica gel inside the box.

**Comment by ghost** [comment]
It may be the seal at the antenna mount -- we did some testing on that and never got any water through but that was under ideal circumstances (no stress on the antenna mount, washer squashed pretty tightly).  Unfortunately there are threads on the antenna jack and the rubber gasket may not perfectly seal out water, especially if there is an accompanied cooling effect on the air inside the plastic enclosure that would cause a vacuum and suck water in.  If the antenna mount is a problem then we could add a step of applying silicone sealant.

**Comment by ghost** [comment]
Using a dessicant would help perhaps in the short term with humidity effects but that's fighting a loosing battle if there is a leak in one of the seals.

**Comment by paularamo** [comment]
We need to test some improvements and check if the water is coming again. If the problem it is not solved after that point we need to create another new issue.
